services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.serving
    container_name: ift6758-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=serving/app.py
      - FLASK_RUN_HOST=0.0.0.0
      - WANDB_API_KEY=${WANDB_API_KEY}

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ift6758-frontend
    ports:
      - "8501:8501"
    environment:
      - FLASK_API_URL=http://backend:5000
    depends_on:
      - backend